/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_11_Operation */

#ifndef _Included_bda_tensorflow_jni_11_Operation
#define _Included_bda_tensorflow_jni_11_Operation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Variable
 * Signature: ([IILbda/tensorflow/jni_11/Scope;Ljava/lang/String;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Variable___3IILbda_tensorflow_jni_111_Scope_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jintArray, jint, jobject, jstring, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Variable
 * Signature: ([IILbda/tensorflow/jni_11/Scope;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Variable___3IILbda_tensorflow_jni_111_Scope_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jintArray, jint, jobject, jstring, jstring, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Identity
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Identity
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Placeholder
 * Signature: (ILbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Placeholder
  (JNIEnv *, jclass, jint, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Transpose
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Transpose
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Conv2D
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;[ILjava/lang/String;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Conv2D
  (JNIEnv *, jclass, jobject, jobject, jintArray, jstring, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    BiasAdd
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_BiasAdd
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Relu
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Relu
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    MaxPool
 * Signature: (Lbda/tensorflow/jni_11/Input;[I[ILjava/lang/String;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_MaxPool
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jstring, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    MatMul
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_MatMul
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Add
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Add
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Mul
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Mul
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Sub
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Sub
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    L2Loss
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_L2Loss
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Mean
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Mean
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    SparseSoftmaxCrossEntropyWithLogits
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_SparseSoftmaxCrossEntropyWithLogits
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Reshape
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Reshape
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Const
 * Signature: ([ILbda/tensorflow/jni/TensorShape;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Const___3ILbda_tensorflow_jni_TensorShape_2Lbda_tensorflow_jni_111_Scope_2Ljava_lang_String_2
  (JNIEnv *, jclass, jintArray, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Const
 * Signature: ([FLbda/tensorflow/jni/TensorShape;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Const___3FLbda_tensorflow_jni_TensorShape_2Lbda_tensorflow_jni_111_Scope_2Ljava_lang_String_2
  (JNIEnv *, jclass, jfloatArray, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    TruncatedNormal
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_TruncatedNormal
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Assign
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Assign
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    AssignSub
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_AssignSub
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    AddSymbolicGradients
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;)[Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobjectArray JNICALL Java_bda_tensorflow_jni_111_Operation_AddSymbolicGradients
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    InTopK
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;ILbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_InTopK
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Gather
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;ZLbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Gather
  (JNIEnv *, jclass, jobject, jobject, jboolean, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    ExpandDims
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_ExpandDims
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Concat
 * Signature: (Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Concat
  (JNIEnv *, jclass, jobject, jobjectArray, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Equal
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Equal
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    ArgMax
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_ArgMax
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Cast
 * Signature: (Lbda/tensorflow/jni_11/Input;ILbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Cast
  (JNIEnv *, jclass, jobject, jint, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Tanh
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Tanh
  (JNIEnv *, jclass, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    Slice
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_Slice
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_Operation
 * Method:    ApplyGradientDescent
 * Signature: (Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;ZLjava/lang/String;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_Operation_ApplyGradientDescent
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
