/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_11_Scope */

#ifndef _Included_bda_tensorflow_jni_11_Scope
#define _Included_bda_tensorflow_jni_11_Scope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_11_Scope
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_Scope_deallocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bda_tensorflow_jni_11_Scope
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_Scope_allocate
  (JNIEnv *, jobject);

/*
 * Class:     bda_tensorflow_jni_11_Scope
 * Method:    toGraphDef
 * Signature: (Lbda/tensorflow/jni/GraphDef;Lbda/tensorflow/jni/Status;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_Scope_toGraphDef
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     bda_tensorflow_jni_11_Scope
 * Method:    toGraph
 * Signature: (Lbda/tensorflow/jni/Graph;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_Scope_toGraph
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
