/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_11_SummaryOperation */

#ifndef _Included_bda_tensorflow_jni_11_SummaryOperation
#define _Included_bda_tensorflow_jni_11_SummaryOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_11_SummaryOperation
 * Method:    HistogramSummary
 * Signature: (Ljava/lang/String;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_SummaryOperation_HistogramSummary
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     bda_tensorflow_jni_11_SummaryOperation
 * Method:    MergeSummary
 * Signature: ([Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_SummaryOperation_MergeSummary
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     bda_tensorflow_jni_11_SummaryOperation
 * Method:    ScalarSummary
 * Signature: (Ljava/lang/String;Lbda/tensorflow/jni_11/Input;Lbda/tensorflow/jni_11/Scope;)Lbda/tensorflow/jni_11/Input;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_111_SummaryOperation_ScalarSummary
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
