/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_11_ClientSession */

#ifndef _Included_bda_tensorflow_jni_11_ClientSession
#define _Included_bda_tensorflow_jni_11_ClientSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_11_ClientSession
 * Method:    allocate
 * Signature: (Lbda/tensorflow/jni_11/Scope;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_ClientSession_allocate
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     bda_tensorflow_jni_11_ClientSession
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_ClientSession_deallocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bda_tensorflow_jni_11_ClientSession
 * Method:    run
 * Signature: ([Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni/Tensor;[Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni/Tensor;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_ClientSession_run___3Lbda_tensorflow_jni_111_Input_2_3Lbda_tensorflow_jni_Tensor_2_3Lbda_tensorflow_jni_111_Input_2_3Lbda_tensorflow_jni_Tensor_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     bda_tensorflow_jni_11_ClientSession
 * Method:    run
 * Signature: ([Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni/Tensor;[Lbda/tensorflow/jni_11/Input;[Lbda/tensorflow/jni/Tensor;Lbda/tensorflow/jni_11/Input;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_111_ClientSession_run___3Lbda_tensorflow_jni_111_Input_2_3Lbda_tensorflow_jni_Tensor_2_3Lbda_tensorflow_jni_111_Input_2_3Lbda_tensorflow_jni_Tensor_2Lbda_tensorflow_jni_111_Input_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
