/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_TensorShape */

#ifndef _Included_bda_tensorflow_jni_TensorShape
#define _Included_bda_tensorflow_jni_TensorShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_TensorShape
 * Method:    allocate
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_TensorShape_allocate
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     bda_tensorflow_jni_TensorShape
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_TensorShape_deallocateMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
