/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_util_Util */

#ifndef _Included_bda_tensorflow_util_Util
#define _Included_bda_tensorflow_util_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_util_Util
 * Method:    addAssignNodeAccordingVariableName
 * Signature: (Lbda/tensorflow/jni/Graph;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_util_Util_addAssignNodeAccordingVariableName
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
