/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_Session */

#ifndef _Included_bda_tensorflow_jni_Session
#define _Included_bda_tensorflow_jni_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_Session
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Session_allocate
  (JNIEnv *, jobject);

/*
 * Class:     bda_tensorflow_jni_Session
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Session_deallocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bda_tensorflow_jni_Session
 * Method:    create
 * Signature: (Lbda/tensorflow/jni/Graph;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Session_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bda_tensorflow_jni_Session
 * Method:    run
 * Signature: ([Ljava/lang/String;[Lbda/tensorflow/jni/Tensor;[Ljava/lang/String;[Ljava/lang/String;[Lbda/tensorflow/jni/Tensor;Lbda/tensorflow/jni/Status;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Session_run
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
