/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_GraphDef */

#ifndef _Included_bda_tensorflow_jni_GraphDef
#define _Included_bda_tensorflow_jni_GraphDef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_GraphDef
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_GraphDef_allocate
  (JNIEnv *, jobject);

/*
 * Class:     bda_tensorflow_jni_GraphDef
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_GraphDef_deallocateMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
