/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_Graph */

#ifndef _Included_bda_tensorflow_jni_Graph
#define _Included_bda_tensorflow_jni_Graph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_Graph
 * Method:    allocate
 * Signature: (Lbda/tensorflow/jni/GraphDef;)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Graph_allocate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     bda_tensorflow_jni_Graph
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bda_tensorflow_jni_Graph_deallocateMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
