/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_input_Input */

#ifndef _Included_bda_tensorflow_jni_input_Input
#define _Included_bda_tensorflow_jni_input_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_input_Input
 * Method:    createImageAndLabelArrayFromFile
 * Signature: (Ljava/lang/String;)[Lbda/tensorflow/jni/input/Record;
 */
JNIEXPORT jobjectArray JNICALL Java_bda_tensorflow_jni_input_Input_createImageAndLabelArrayFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bda_tensorflow_jni_input_Input
 * Method:    sample
 * Signature: ([Lbda/tensorflow/jni/input/Record;[I)[Lbda/tensorflow/jni/Tensor;
 */
JNIEXPORT jobjectArray JNICALL Java_bda_tensorflow_jni_input_Input_sample
  (JNIEnv *, jclass, jobjectArray, jintArray);

/*
 * Class:     bda_tensorflow_jni_input_Input
 * Method:    convertToRecord
 * Signature: (B[F)Lbda/tensorflow/jni/input/Record;
 */
JNIEXPORT jobject JNICALL Java_bda_tensorflow_jni_input_Input_convertToRecord
  (JNIEnv *, jclass, jbyte, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
