/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bda_tensorflow_jni_Node */

#ifndef _Included_bda_tensorflow_jni_Node
#define _Included_bda_tensorflow_jni_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bda_tensorflow_jni_Node
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bda_tensorflow_jni_Node_name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
